onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_top/PCLK
add wave -noupdate /tb_top/u_wrap/u_dut/MOSI
add wave -noupdate /tb_top/u_wrap/u_dut/MISO
add wave -noupdate /tb_top/u_wrap/u_dut/SS_n
add wave -noupdate /tb_top/u_wrap/u_dut/IRQ
add wave -noupdate /tb_top/u_wrap/u_dut/tx_empty
add wave -noupdate /tb_top/u_wrap/u_dut/tx_pop
add wave -noupdate /tb_top/u_wrap/u_dut/rx_push_valid
add wave -noupdate /tb_top/u_wrap/u_dut/rx_push_data
add wave -noupdate /tb_top/u_wrap/u_dut/busy
add wave -noupdate /tb_top/u_wrap/u_dut/transfer_done_pulse
add wave -noupdate /tb_top/u_wrap/u_dut/ss_n_int
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/PRESETn
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/PSEL
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/PENABLE
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/PWRITE
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/PADDR
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/PRDATA
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/PREADY
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/PSLVERR
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/cfg_en
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/cfg_mstr
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/cfg_mode
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/cfg_lsb_first
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/cfg_loopback
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/cfg_width
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/cfg_clk_div
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/cfg_delay
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/SS_n
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/tx_word
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/tx_empty
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/tx_pop
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/rx_push_valid
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/rx_push_data
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/busy_in
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/transfer_done_pulse
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/IRQ
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/ctrl_en
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/ctrl_mstr
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/ctrl_mode
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/ctrl_lsb_first
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/ctrl_loopback
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/ctrl_width
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/clk_div
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/ss_en
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/ss_val
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/int_en
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/int_stat
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/delay_cfg
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/apb_access
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/apb_write
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/apb_read
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/tx_wp
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/tx_rp
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/tx_count
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/tx_full_w
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/tx_empty_w
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/rx_wp
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/rx_rp
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/rx_count
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/rx_full_w
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/rx_empty_w
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/status_word
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/ctrl_word
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/ss_ctrl_word
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/int_en_word
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/PCLK
add wave -noupdate -color Gold /tb_top/u_wrap/u_dut/u_regfile/PWDATA
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/int_stat_word
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/clk_div_word
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/delay_word
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/rx_pop_this_cycle
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/tx_push_valid
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/tx_push_data
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/tx_push_accepted
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/tx_push_dropped
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/i
add wave -noupdate /tb_top/u_wrap/u_dut/u_regfile/int_stat_update/next_stat
add wave -noupdate -expand /tb_top/u_wrap/u_dut/u_regfile/tx_mem
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1095090 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 340
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {952322 ps} {1466484 ps}
